#!/usr/bin/env bash
# displays Best School 10 times but Hi on the 9th.

COUNTER=0
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER -eq 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((COUNTER++))
done